In [1]:
import pandas as pd
import scipy.stats as stats
def chi_square_test(data, col1, col2):
    contingency_table = pd.crosstab(data[col1], data[col2])
    chi2, p, dof, expected = stats.chi2_contingency(contingency_table)
    return chi2, p, dof, expected

In [2]:
from google.colab import files
uploaded = files.upload()  # Upload CSV file manually
file_name = list(uploaded.keys())[0]  # Get the uploaded filename

# Specify the encoding when reading the CSV file
df = pd.read_csv(file_name, encoding='latin-1')

print("Dataset Loaded Successfully!\n", df.head())

Saving exp4.csv to exp4.csv
Dataset Loaded Successfully!
    Restaurant_ID             Name   Cuisine  Rating Price_Range  \
0              1  The Spice House    Indian     4.5      Medium   
1              2     Bella Italia   Italian     4.2        High   
2              3    Golden Dragon   Chinese     4.7        High   
3              4   The Burger Hub  American     3.8      Medium   
4              5  Fiesta Mexicana   Mexican     4.1         Low   

   Customer_Count  Revenue  Delivery_Time  Location  
0             200     4500             30     Urban  
1             120     6000             40     Urban  
2             180     7200             25     Urban  
3             250     5000             20  Suburban  
4             300     3500             35  Suburban  


In [3]:
# Perform chi-square test between 'Price_Range' and 'Location'
# 'df' is the DataFrame that holds the loaded CSV data
chi2, p, dof, expected = chi_square_test(df, 'Price_Range', 'Location')

print("Chi-Square Value:", chi2)
print("P-Value:", p)
print("Degrees of Freedom:", dof)
print("Expected Frequency Table:\n", expected)

Chi-Square Value: 12.280303030303031
P-Value: 0.015384150029806129
Degrees of Freedom: 4
Expected Frequency Table:
 [[1.05 2.1  3.85]
 [0.75 1.5  2.75]
 [1.2  2.4  4.4 ]]


In [4]:
import numpy as np
import scipy.stats as stats

In [5]:
# Update observed values based on function-based contingency table
observed = np.array([[0, 0, 7],  # High
                     [2, 3, 0],  # Low
                     [1, 3, 4]]) # Medium


In [6]:
# Compute the row and column sums
row_sums = observed.sum(axis=1, keepdims=True)
col_sums = observed.sum(axis=0, keepdims=True)
total = observed.sum()


In [7]:
# Compute expected frequencies
expected = (row_sums @ col_sums) / total

In [8]:
# Compute Chi-Square statistic
chi2_stat = ((observed - expected) ** 2 / expected).sum()

In [9]:
# Degrees of Freedom = (rows - 1) * (columns - 1)
dof = (observed.shape[0] - 1) * (observed.shape[1] - 1)

In [10]:
# Compute p-value
p_value = 1 - stats.chi2.cdf(chi2_stat, dof)

print("Chi-Square Statistic:", chi2_stat)
print("Degrees of Freedom:", dof)
print("P-Value:", p_value)
print("Expected Frequency Table:\n", expected)

Chi-Square Statistic: 12.280303030303031
Degrees of Freedom: 4
P-Value: 0.015384150029806087
Expected Frequency Table:
 [[1.05 2.1  3.85]
 [0.75 1.5  2.75]
 [1.2  2.4  4.4 ]]


In [11]:
print("Contingency Table (Function-Based):\n", pd.crosstab(df['Price_Range'], df['Location'])) # Changed 'data' to 'df'
print("Observed Table (Hardcoded):\n", observed)
print("Expected (Function-Based):\n", expected)

Contingency Table (Function-Based):
 Location     Rural  Suburban  Urban
Price_Range                        
High             0         0      7
Low              2         3      0
Medium           1         3      4
Observed Table (Hardcoded):
 [[0 0 7]
 [2 3 0]
 [1 3 4]]
Expected (Function-Based):
 [[1.05 2.1  3.85]
 [0.75 1.5  2.75]
 [1.2  2.4  4.4 ]]
